### PR TITLE
Added Runic Enchantments

### PR DESCRIPTION
**Pull request by Draco18s**

### CODE REVIEW

**Comment by Draco18s** [comment]
Not sure what's up with the AppVeyor build, it looks like its an issue in code I didn't even touch.

**Comment by Timwi** [comment]
Hello! I’m about to merge your changes and include Runic in EsotericIDE. I can’t find an entry for it on esolangs.org. Do you have documentation on how your language works so I can test it?

(And don’t worry about the AppVeyor error, that’s due to changes in RT.Util — I’ll fix that)

**Comment by Timwi** [comment]
I’ve now merged it and auto-reformatted all of the files (sorry). I also made a few minor fixes listed in the commit description. Thanks for your contribution!

**Comment by Draco18s** [comment]
Yep, I've got a readme:
https://github.com/Draco18s/RunicEnchantments/tree/Console/RunicInterpreter/draco18s/runic

**Pull request merged**
